// Copyright 2026 Jason Smathers
// SPDX-License-Identifier: Apache-2.0

export {
  ArtifactIndexSchema,
  ArtifactPathSchema,
  ArtifactReferenceSchema,
  type ArtifactIndex,
  type ArtifactReference,
} from './artifacts.js';
export {
  AgeBasisSchema,
  AgeDivisionSchema,
  AgeDivisionSetSchema,
  CompetitionLevelSchema,
  CompetitionRegionSchema,
  DisciplineSchema,
  EquipmentCategorySchema,
  SexCategorySchema,
  WeightClassLadderSchema,
  WeightClassSchema,
  type AgeBasis,
  type AgeDivision,
  type AgeDivisionSet,
  type CompetitionLevel,
  type CompetitionRegion,
  type Discipline,
  type EquipmentCategory,
  type SexCategory,
  type WeightClass,
  type WeightClassLadderData,
} from './categories.js';
export {
  ATHLETE_SHARD_COUNT,
  athleteArtifactId,
  athleteLookupKey,
  athleteShardBucket,
} from './athlete-shards.js';
export {
  ATHLETE_MIRROR_ARTIFACT_ID,
  AthleteAgeSchema,
  AthleteEntrySchema,
  AthleteHistorySchema,
  AthleteMirrorInfoSchema,
  AthleteShardSchema,
  findAthleteHistories,
  type AthleteAge,
  type AthleteEntry,
  type AthleteHistory,
  type AthleteMirrorInfo,
  type AthleteShard,
} from './athletes.js';
export {
  CategoryCatalogSchema,
  categoryCatalogArtifactId,
  type CategoryCatalog,
} from './catalog.js';
export {
  ClassificationBookSchema,
  ClassificationScopeSchema,
  ClassificationStandardSchema,
  ClassificationTableSchema,
  type ClassificationBook,
  type ClassificationScope,
  type ClassificationStandard,
  type ClassificationTable,
} from './classification.js';
export {
  classificationArtifactId,
  classificationShardKey,
  sameClassificationShard,
  type ClassificationShardKey,
} from './classification-shards.js';
export {
  ConversionChartSchema,
  ConversionRowSchema,
  ConversionSourceSchema,
  conversionChartArtifactId,
  type ConversionChartData,
  type ConversionRow,
  type ConversionSource,
} from './conversions.js';
export {
  DataMetaSchema,
  SourceFreshnessSchema,
  type DataMeta,
  type SourceFreshness,
} from './freshness.js';
export {
  AutomaticAttemptBehaviourSchema,
  FormatOverrideSchema,
  FourthAttemptSchema,
  MEET_RULES_ARTIFACT_ID,
  MeetFormatSchema,
  MeetRuleBookSchema,
  MeetRuleProfileSchema,
  MeetRuleSourceSchema,
  OpenerChangeSchema,
  PlatformLiftSchema,
  ThirdAttemptChangeSchema,
  TieBreakStepSchema,
  type AutomaticAttemptBehaviour,
  type MeetFormat,
  type MeetRuleBook,
  type MeetRuleProfile,
  type MeetRuleSource,
  type PlatformLift,
  type TieBreakStep,
} from './meet-rules.js';
export {
  ClassificationRequirementSchema,
  DisputedReadingSchema,
  GearQualificationSchema,
  MeetOfferingSchema,
  PointsRequirementSchema,
  PointsThresholdSchema,
  QUALIFYING_MEETS_ARTIFACT_ID,
  QualifyingConditionSchema,
  QualifyingDisputeSchema,
  QualifyingEntrySchema,
  QualifyingFederationRulesSchema,
  QualifyingMeetBookSchema,
  QualifyingMeetSchema,
  QualifyingPerformanceSchema,
  QualifyingRouteSchema,
  QualifyingRulebookSchema,
  QualifyingSourceSchema,
  QualifyingStandardSchema,
  QualifyingWindowSchema,
  StandardDivisionBasisSchema,
  TestedOfferingSchema,
  WeightClassEntryRuleSchema,
  findQualifyingFederationRules,
  type DisputedReading,
  type GearQualification,
  type MeetOffering,
  type PointsThreshold,
  type QualifyingCondition,
  type QualifyingDispute,
  type QualifyingEntry,
  type QualifyingFederationRules,
  type QualifyingMeet,
  type QualifyingMeetBook,
  type QualifyingPerformance,
  type QualifyingRoute,
  type QualifyingRulebook,
  type QualifyingSource,
  type QualifyingStandard,
  type QualifyingWindow,
  type StandardDivisionBasis,
  type TestedOffering,
  type WeightClassEntryRule,
} from './qualification.js';
export {
  recordArtifactId,
  recordShardKey,
  sameRecordShard,
  type RecordShardKey,
} from './record-shards.js';
export {
  FederationRecordSchema,
  LiftSchema,
  RecordBookSchema,
  RecordScopeSchema,
  RecordSourceTableSchema,
  findRecordSourceTable,
  type FederationRecord,
  type Lift,
  type RecordBook,
  type RecordScope,
  type RecordSourceTable,
} from './records.js';
