// Copyright 2026 Jason Smathers
// SPDX-License-Identifier: Apache-2.0

export {
  ATTEMPT_PLAN_METHODOLOGY_VERSION,
  ATTEMPT_RISKS,
  DATA_CONFIDENCES,
  assessDataConfidence,
  classifyAttemptRisk,
  isRiskierThan,
  type AttemptRisk,
  type AttemptRiskQuery,
  type ConfidenceEvidence,
  type ConfidenceReason,
  type ConfidenceReasonCode,
  type DataConfidence,
  type DataConfidenceAssessment,
  type EvidenceAge,
  type MaximumSource,
  type Readiness,
} from './attempt-risk.js';
export {
  RESEARCH_BASIS_NOTE,
  reviewJumps,
  type JumpAdvisory,
  type JumpAdvisoryCode,
  type JumpAdvisorySeverity,
  type JumpEvidence,
  type JumpPopulation,
  type JumpSequence,
  type ResearchComparison,
} from './attempt-jumps.js';
export {
  MEET_GOALS,
  percentagesFor,
  planAttempts,
  strategyForGoal,
  type AttemptPlan,
  type AttemptPlanProblem,
  type AttemptPlanProblemCode,
  type AttemptPlanRequest,
  type AttemptPlanResult,
  type MeetGoal,
  type PercentBand,
  type PlanStrategy,
  type PlannedAttempt,
  type RoundingNote,
  type RoundingReason,
  type StrategyPercentages,
} from './attempt-plan.js';
export {
  admitsAge,
  competitionAge,
  eligibleAgeDivisions,
  findAgeDivisionProblems,
  narrowestAgeDivision,
  openAgeDivision,
  type AgeDivisionProblem,
  type OpenAgeDivisionResult,
} from './age-division.js';
export {
  KILOGRAM_MILESTONES,
  POUND_MILESTONES,
  milestonesFor,
  standingAmongMilestones,
  type BarbellMilestone,
  type MilestoneChart,
  type MilestoneStanding,
} from './barbell-milestones.js';
export {
  ClassificationLadder,
  selectClassificationTable,
  type Classification,
  type ClassificationLadderProblem,
  type ClassificationLadderProblemCode,
  type ClassificationLadderResult,
  type ClassificationQuery,
  type ClassificationTableSelection,
} from './classification.js';
export {
  chartColumnFor,
  convertAgainstChart,
  convertMilestones,
  directionFrom,
  directionInputUnit,
  directionOutputUnit,
  filterRowsByStep,
  nearestRowIndex,
  reverseDirection,
  rowWeight,
  type ConversionAnswer,
  type ConversionDirection,
  type MilestoneConversion,
} from './conversion.js';
export {
  ConversionChart,
  type ChartColumn,
  type ChartLookup,
  type ConversionChartGap,
  type ConversionChartProblem,
  type ConversionChartProblemCode,
  type ConversionChartResult,
} from './conversion-chart.js';
export {
  LIFTS,
  PRIMARY_LIFTS,
  findLift,
  liftsByGroup,
  type LiftDefinition,
  type LiftGroup,
} from './lifts.js';
export {
  MAX_ATTEMPT_NOTE_LENGTH,
  UNDO_HISTORY_LIMIT,
  applyMeetAction,
  attemptsOn,
  bestGoodLift,
  bombOutRisk,
  changeAllowanceFor,
  createMeetDocument,
  findAttempt,
  findLifter,
  isResolved,
  jumpFromPrevious,
  liftsInFormat,
  nextAttemptOn,
  outstandingExtraAttempts,
  projectedTotalWith,
  startTimeline,
  submissionState,
  takenOn,
  totalSoFar,
  undo,
  undoableAction,
  type AttemptEffort,
  type AttemptKind,
  type AttemptLights,
  type AttemptStatus,
  type BombOutRisk,
  type LiveAttempt,
  type LiveLifter,
  type MeetAction,
  type MeetActionProblem,
  type MeetActionProblemCode,
  type MeetActionResult,
  type MeetDocument,
  type MeetTimeline,
  type MissReason,
  type RecordedResult,
  type RefereeLight,
  type ResolvedStatus,
  type RunningTotal,
  type SubmissionCountdown,
  type SubmissionState,
  type SubmissionStatus,
  type UndoStep,
} from './meet-document.js';
export {
  MeetRules,
  type AttemptFloorReason,
  type AttemptLegality,
  type AttemptOutcome,
  type AttemptRefusalCode,
  type AutomaticAttempt,
  type ChangeAllowance,
  type ChangeConditionCode,
  type FourthAttemptBlockCode,
  type FourthAttemptEligibility,
  type LegalWeightsAround,
  type MeetRuleProblem,
  type MeetRuleProblemCode,
  type MeetRulesResult,
  type NextAttemptBounds,
  type TakenAttempt,
} from './meet-rules.js';
export {
  LOADING_TOLERANCE,
  buildLoadingTable,
  emptyImplement,
  findLoading,
  plateChange,
  type BarbellSetup,
  type FindLoadingOptions,
  type Loading,
  type LoadingBound,
  type LoadingTable,
  type PlateChange,
  type PlateDenomination,
} from './plates.js';
export {
  MAX_COMPLETED_REPS,
  MIN_COMPLETED_REPS,
  ONE_REP_MAX_METHODOLOGY_VERSION,
  ROUNDING_INCREMENTS,
  defaultRoundingIncrement,
  estimateOneRepMax,
  type EstimatedMax,
  type FormQuality,
  type FormulaDisagreement,
  type FormulaOutcome,
  type InputGrade,
  type ObservedSingle,
  type OneRepMaxAdvisory,
  type OneRepMaxAdvisoryCode,
  type OneRepMaxEstimate,
  type OneRepMaxProblem,
  type OneRepMaxProblemCode,
  type OneRepMaxRequest,
  type OneRepMaxResult,
  type OutcomeReasonCode,
  type ReportedSex,
  type RepsInReserve,
  type SetFreshness,
  type TrainingExperience,
  type WithheldEstimate,
  type WithheldReasonCode,
} from './one-rep-max.js';
export {
  DEFAULT_PERCENTAGE_STEP,
  PERCENTAGE_STEPS,
  trainingPercentages,
  type PercentageOptions,
  type TrainingPercentage,
} from './one-rep-max-percentages.js';
export {
  ESTIMATE_LIFTS,
  FORMULAS,
  PROMINENT_LIFTS,
  evaluateFormula,
  findFormula,
  formulasInTier,
  type EstimateLift,
  type FormulaDefinition,
  type FormulaFamily,
  type FormulaId,
  type FormulaInput,
  type FormulaTier,
} from './one-rep-max-formulas.js';
export {
  defaultTechniqueFor,
  findTechnique,
  techniquesFor,
  type TechniqueMatch,
  type TechniqueOption,
} from './one-rep-max-technique.js';
export {
  comparePlainDates,
  completedYearsBetween,
  formatPlainDate,
  formatPlainDateLong,
  parsePlainDate,
  type ParsedPlainDate,
  type PlainDate,
} from './plain-date.js';
export {
  findRecord,
  recordTargets,
  standingAgainstRecord,
  type RecordLookup,
  type RecordMarginRules,
  type RecordQuery,
  type RecordStanding,
  type RecordTarget,
  type RecordTargetBasis,
  type RecordTargets,
} from './records.js';
export {
  USPA_POUNDS_PER_KILOGRAM,
  kilogramsToUspaDisplayPounds,
  parseKilograms,
  type ParsedKilograms,
} from './units.js';
export {
  planWarmup,
  type WarmupAdvisory,
  type WarmupAdvisoryCode,
  type WarmupFamily,
  type WarmupPlan,
  type WarmupPlanResult,
  type WarmupProblem,
  type WarmupProblemCode,
  type WarmupRequest,
  type WarmupSet,
  type WarmupStage,
  type WorkingSetLoad,
  type WorkingSetPlan,
} from './warmup.js';
export {
  adjustWarmups,
  isAdjustable,
  nudgeWarmup,
  warmupSteps,
  type WarmupAdjustment,
  type WarmupStep,
} from './warmup-adjust.js';
export {
  KILOGRAMS_PER_POUND,
  convertWeight,
  enterWeight,
  entryAmount,
  entryWeight,
  formatWeight,
  formatWeightAt,
  retypeEntry,
  roundForDisplay,
  roundToPlaces,
  showEntryIn,
  weightIn,
  type EnteredWeight,
  type Weight,
  type WeightUnit,
} from './weight.js';
export {
  MAX_WEIGHT_INPUT,
  parseWeightInput,
  type ParsedWeightInput,
  type WeightInputProblem,
} from './weight-input.js';
export {
  WeightClassLadder,
  type WeightClassFit,
  type WeightClassLadderProblem,
  type WeightClassLadderProblemCode,
  type WeightClassLadderResult,
} from './weight-class.js';
