// Copyright 2026 Jason Smathers
// SPDX-License-Identifier: Apache-2.0

/**
 * Saying that the rest is up in the three ways a phone can say it. Section 7.11.
 *
 * A tone, a buzz, and a notification. Section 7.11 has all three as things the timer
 * *may* do "only when supported and affirmatively enabled", and the whole difficulty
 * of the feature is in those two conditions rather than in making the noise.
 *
 * ON THIS DEVICE, AND NOTHING ELSE
 *
 * Nothing here reaches the network and nothing here registers a service worker. The
 * tone is generated by an oscillator, so there is no audio file to fetch and none
 * inlined into the bundle either -- a base64 wav is a hundred kilobytes carried by
 * every lifter to make two beeps that thirty lines of arithmetic make better. The
 * notification is one this page constructs and shows itself: a push notification is
 * the other kind, and it needs a subscription, a server, and an endpoint that knows
 * this lifter exists. There is no such server and there will not be one.
 *
 * WHY THE DEVICE IS SUPPLIED AND NOT REACHED FOR
 *
 * `storage/persistence.ts`'s rule, for its reasons: the words `AudioContext`,
 * `navigator` and `Notification` appear in exactly one function below, a test hands in
 * three closures rather than monkey-patching globals another test in the same file
 * shares, and a host that already owns a sound may pass its own.
 *
 * WHAT A CHANNEL CAN COME BACK WITH
 *
 * Three outcomes and not two. `refused` is the device saying no in a way that can be
 * read -- notifications blocked, vibration returning `false`, an audio context the
 * browser will not start. `unknown` is everything else: the prompt dismissed without
 * an answer, a constructor that threw, an API present and silent about whether it did
 * anything. A screen that reported the second as the first would tell a lifter they had
 * refused something they never saw.
 *
 * **Unsupported is a fourth thing and it never reaches an outcome.** A channel this
 * device has no API for is left out of {@link RestAlerter.channels}, so it is never
 * offered, never enabled, and never reported as having failed. Section 0.4: a control
 * that stands in for a feature it cannot deliver is worse than its absence.
 */

import type { RestAlertChannel, RestAlertSettings } from '../types.js';

/** What came of trying one channel. See the note above. */
export type RestAlertOutcome = 'delivered' | 'refused' | 'unknown';

/**
 * An outcome that is not a delivery.
 *
 * Named apart from {@link RestAlertOutcome} so that a report of what went wrong cannot
 * be built holding a success, and so the copy is a total function of it.
 */
export type RestAlertFailure = Exclude<RestAlertOutcome, 'delivered'>;

/** One channel that did not do what it offered to do. */
export interface RestAlertTrouble {
  readonly channel: RestAlertChannel;
  readonly failure: RestAlertFailure;
}

/** The permission states the Notifications API has. */
export type RestNotifyPermission = 'default' | 'granted' | 'denied';

/**
 * The slice of the Notifications API this needs.
 *
 * `permission()` is a function and not a field because it is read at every firing: a
 * lifter may revoke the permission from the address bar between switching the alert on
 * and finishing their set, and a snapshot taken at construction would go on claiming
 * the notification was delivered.
 */
export interface RestNotifier {
  permission(): RestNotifyPermission;
  /** Only ever from a press. See {@link RestAlerter.arm}. */
  request(): Promise<RestNotifyPermission>;
  /** Show one now. Throws where the platform refuses to construct it. */
  post(title: string): void;
}

/**
 * What the host can actually do, with an absent member meaning "not on this device".
 *
 * `tone` answers whether it played, which is not the same as whether it was heard --
 * the ringer switch is not readable from a page, so a phone on silent reports a
 * delivered tone and stays quiet. That is the one failure this file cannot detect, and
 * the option's own description on screen is where it is admitted.
 */
export interface RestAlertDevice {
  readonly tone?: (() => Promise<boolean>) | undefined;
  /** The platform's own contract: `false` means the pattern was not accepted. */
  readonly vibrate?: ((pattern: readonly number[]) => boolean) | undefined;
  readonly notifications?: RestNotifier | undefined;
}

export interface RestAlerter {
  /** The channels this device can do at all, in a fixed order. Possibly none. */
  readonly channels: readonly RestAlertChannel[];

  /**
   * Turn one channel on, from the press that turned it on, and demonstrate it.
   *
   * The permission ask lives here and nowhere else. Section 10.3's rule for storage,
   * applied to a second prompt: asked on load it is a dialog thrown at somebody who
   * has not yet logged a set, and the answer to a dialog nobody asked for is no --
   * permanently, from a person who would have said yes at the end of the session.
   *
   * It also *fires* the channel rather than only enabling it, which is the only way a
   * lifter finds out in the gym car park instead of at the rack. Two of the three fail
   * silently on a phone and invisibly on a desktop, and a switch that turns on and then
   * does nothing is worse than no switch.
   */
  arm(channel: RestAlertChannel, title: string): Promise<RestAlertOutcome>;

  /**
   * Say the rest is up on every channel that is on, and report the ones that did not.
   *
   * Asks for nothing. There is no user gesture behind a countdown reaching zero, so a
   * permission request here would be suppressed by the browser anyway -- and a channel
   * whose permission has gone away since it was armed is reported, not re-requested.
   */
  fire(alerts: RestAlertSettings, title: string): Promise<readonly RestAlertTrouble[]>;
}

/** The order the channels are offered in, loudest last. */
const CHANNELS: readonly RestAlertChannel[] = ['vibrate', 'sound', 'notify'];

/**
 * Buzz, gap, buzz, in milliseconds.
 *
 * Two pulses rather than one long one, because a single 400ms buzz in a pocket is
 * indistinguishable from every message the phone has had all day.
 */
const BUZZ_PATTERN: readonly number[] = [180, 90, 180];

export function createRestAlerter(device: RestAlertDevice): RestAlerter {
  const channels = CHANNELS.filter((channel) => supported(device, channel));

  async function sound(): Promise<RestAlertOutcome> {
    const tone = device.tone;
    if (tone === undefined) return 'unknown';
    try {
      return (await tone()) ? 'delivered' : 'refused';
    } catch {
      return 'unknown';
    }
  }

  function buzz(): RestAlertOutcome {
    const vibrate = device.vibrate;
    if (vibrate === undefined) return 'unknown';
    try {
      return vibrate(BUZZ_PATTERN) ? 'delivered' : 'refused';
    } catch {
      return 'unknown';
    }
  }

  /**
   * `ask` is what separates a press from a countdown; see the two methods above.
   *
   * A `default` permission that survives the ask is `unknown` and not `refused`: the
   * prompt was dismissed rather than answered, which is the distinction the settings
   * screen already draws between never having asked for persistent storage and having
   * been told no.
   */
  async function notify(title: string, ask: boolean): Promise<RestAlertOutcome> {
    const notifier = device.notifications;
    if (notifier === undefined) return 'unknown';

    let permission = notifier.permission();
    if (permission === 'default' && ask) {
      try {
        permission = await notifier.request();
      } catch {
        return 'unknown';
      }
    }
    if (permission === 'denied') return 'refused';
    if (permission !== 'granted') return 'unknown';

    try {
      notifier.post(title);
      return 'delivered';
    } catch {
      // Android's Chrome throws here rather than showing anything: it will only take a
      // notification from a service worker, which this tool does not have and will not
      // get. Reported as `unknown` and caught at the press, so the switch goes back off
      // in front of the lifter instead of three minutes later in a pocket.
      return 'unknown';
    }
  }

  async function deliver(
    channel: RestAlertChannel,
    title: string,
    ask: boolean,
  ): Promise<RestAlertOutcome> {
    switch (channel) {
      case 'sound':
        return sound();
      case 'vibrate':
        return buzz();
      case 'notify':
        return notify(title, ask);
    }
  }

  return {
    channels,

    async arm(channel, title) {
      if (!supported(device, channel)) return 'unknown';
      return deliver(channel, title, true);
    },

    async fire(alerts, title) {
      const trouble: RestAlertTrouble[] = [];
      for (const channel of channels) {
        if (!alerts[channel]) continue;
        // Sequential, and the await is the point rather than an oversight: two of the
        // three are a single call, and the third posts a notification whose permission
        // check must not race a second channel's. Three at most, so there is nothing
        // to win by starting them together.
        const outcome = await deliver(channel, title, false);
        if (outcome !== 'delivered') trouble.push({ channel, failure: outcome });
      }
      return trouble;
    },
  };
}

function supported(device: RestAlertDevice, channel: RestAlertChannel): boolean {
  switch (channel) {
    case 'sound':
      return device.tone !== undefined;
    case 'vibrate':
      return device.vibrate !== undefined;
    case 'notify':
      return device.notifications !== undefined;
  }
}

/** One channel switched on or off, as a new settings object. */
export function withChannel(
  alerts: RestAlertSettings,
  channel: RestAlertChannel,
  on: boolean,
): RestAlertSettings {
  return { ...alerts, [channel]: on };
}

/**
 * The two pips, in hertz, and how long each one lasts.
 *
 * A fifth apart and short. A single tone at gym volume reads as a phone doing something
 * generic; two rising pips are the shape of a finished timer, and 160ms each is over
 * before it can annoy anybody on the next platform.
 */
const PIP_HERTZ: readonly number[] = [880, 1319];
const PIP_SECONDS = 0.16;
const PIP_GAP_SECONDS = 0.06;

/**
 * Peak gain, well under 1.
 *
 * A sine at full scale through a phone speaker clips, and the clipping is what makes a
 * generated tone sound like a fault rather than a chime.
 */
const PIP_GAIN = 0.18;

/**
 * Two pips, scheduled on the context's own clock.
 *
 * Scheduled ahead rather than played and timed with `setTimeout`, because the audio
 * thread keeps time whether or not the main thread is throttled -- and this fires on a
 * page that has very likely just been backgrounded.
 *
 * Each pip is ramped up and down rather than switched. A gain that jumps from zero is a
 * click, and at this length the click is most of what is heard.
 */
function playPips(context: AudioContext): void {
  const start = context.currentTime;
  PIP_HERTZ.forEach((hertz, index) => {
    const at = start + index * (PIP_SECONDS + PIP_GAP_SECONDS);
    const oscillator = context.createOscillator();
    const gain = context.createGain();
    oscillator.type = 'sine';
    oscillator.frequency.setValueAtTime(hertz, at);
    gain.gain.setValueAtTime(0, at);
    gain.gain.linearRampToValueAtTime(PIP_GAIN, at + 0.01);
    gain.gain.linearRampToValueAtTime(0, at + PIP_SECONDS);
    oscillator.connect(gain).connect(context.destination);
    oscillator.start(at);
    oscillator.stop(at + PIP_SECONDS);
  });
}

/**
 * The three channels as this browser offers them, with the absent ones absent.
 *
 * The only function in this package that touches an audio, vibration or notification
 * global. Called from the element's default, so a consumer who supplies their own
 * device never evaluates any of it.
 */
export function browserRestAlertDevice(): RestAlertDevice {
  return {
    tone: browserTone(),
    vibrate: browserVibrate(),
    notifications: browserNotifier(),
  };
}

/**
 * One `AudioContext`, made on the first tone and kept.
 *
 * Kept because a browser allows a small number of them per page -- six in Chromium --
 * and a context per rest would stop making sound partway through a session. Made late
 * because a context constructed at load, before the page has been touched, starts
 * suspended and counts against that limit while doing nothing.
 *
 * `resume()` is what the autoplay policy wants, and it is why {@link RestAlerter.arm}
 * matters: the first tone is played from a press, which unlocks the context for the
 * life of the page, so the tone three minutes later needs no gesture of its own.
 */
function browserTone(): (() => Promise<boolean>) | undefined {
  if (!('AudioContext' in globalThis)) return undefined;
  let context: AudioContext | null = null;
  return async (): Promise<boolean> => {
    context ??= new AudioContext();
    if (context.state === 'suspended') await context.resume();
    if (context.state !== 'running') return false;
    playPips(context);
    return true;
  };
}

/**
 * `navigator.vibrate`, where there is one.
 *
 * Typed as always present by the DOM lib and absent on desktop Safari, which is why the
 * test is `in` rather than a comparison the compiler would call dead. Present is not the
 * same as effective: a desktop Chrome has the method, accepts the pattern, and has
 * nothing to vibrate. Nothing can be read back about that, so the option says so.
 *
 * Copied into a mutable array because the platform's signature will not take a
 * `readonly` one, and handing it the module's own constant would let it be rewritten.
 */
function browserVibrate(): ((pattern: readonly number[]) => boolean) | undefined {
  if (!('vibrate' in navigator)) return undefined;
  return (pattern) => navigator.vibrate([...pattern]);
}

/**
 * The page's own `Notification`, never a service worker's.
 *
 * `requestPermission()` is called only from {@link RestAlerter.arm}, and the constructor
 * is what throws on Android; both are handled by the alerter above rather than here, so
 * that a supplied device gets the same treatment as this one.
 */
function browserNotifier(): RestNotifier | undefined {
  if (!('Notification' in globalThis)) return undefined;
  return {
    permission: () => Notification.permission,
    request: () => Notification.requestPermission(),
    post: (title) => {
      new Notification(title);
    },
  };
}

/** The alerter the element uses unless it is handed one. One per page; see the context. */
let shared: RestAlerter | null = null;

export function defaultRestAlerter(): RestAlerter {
  shared ??= createRestAlerter(browserRestAlertDevice());
  return shared;
}
